account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.logout_user, name='logout_user'),
    path('register/', views.user_register, name='user_register'),
    path('profile/edit/', views.edit_profile, name='profile_edit')
]

laptop_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from laptop_shop import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('pages.urls')),
                  path('', include('account.urls')),
                  path('product/', include('products.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import HomePageView, ContactView, AboutPageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
]

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Laptop_Shop</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<!-- Libraries Stylesheet -->
<link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

<!-- Customized Bootstrap Stylesheet -->
<link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body>
<!-- Topbar Start -->
<div class="container-fluid">
    <div class="row bg-secondary py-1 px-xl-5">
        <div class="col-lg-6 d-none d-lg-block">
            <div class="d-inline-flex align-items-center h-100">
                <a class="text-body mr-3" href="{% url 'contact' %}">Contact</a>
             
                <!-- <a class="text-body mr-3" href="">Help</a> -->
                <!-- <a class="text-body mr-3" href="">FAQs</a> -->
            </div>
        </div>
        <div class="col-lg-6 text-center text-lg-right">
            <div class="d-inline-flex align-items-center">
                <div class="btn-group">

                </div>
            </div>
           
        </div>
    </div>
    <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
        <div class="col-lg-4">
            <a href="" class="text-decoration-none">
                <span class="h1 text-uppercase text-primary bg-dark px-2">Laptop</span>
                <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">Shop</span>
            </a>
        </div>
        <div class="col-lg-4 col-6 text-left">
            <form class="d-flex mx-3" action="{% url 'product_search' %}" method="get">
                <input class="form-control form-control-sm mr-2" type="search" name="query" placeholder="Search product...">
                <button class="btn btn-primary btn-sm" type="submit"><i class="fa fa-search"></i></button>
            </form>
            {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
        {% endif %}
            
        </div>
        <div class="col-lg-4 col-6 text-right">
            <p class="m-0">AM Coder</p>
            <h5 class="m-0">+989339796368</h5>
        </div>
        
    </div>
</div>
<!-- Topbar End -->
<!-- Navbar Start -->
<div class="container-fluid bg-dark mb-30">
    <div class="row px-xl-5">
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                <!-- Brand Logo -->
                <a href="{% url 'home' %}" class="text-decoration-none d-block d-lg-none">
                    <span class="h1 text-uppercase text-dark bg-light px-2">Multi</span>
                    <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">Shop</span>
                </a>
                
                <!-- Mobile Menu Toggle Button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <!-- Navbar Items -->
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <ul class="navbar-nav ml-auto align-items-center">
                            {% if request.user.is_authenticated %}
                                <li class="nav-item dropdown ml-auto">
                                    <a class="nav-link dropdown-toggle text-white d-flex align-items-center" href="#" id="userDropdown" role="button" data-toggle="dropdown">
                                        {% if user.profile.image %}
                                            <img src="{{ user.profile.image.url }}" height="30px" width="30px" class="rounded-circle">
                                        {% else %}
                                            <i class="fa fa-user-circle fa-lg"></i>
                                        {% endif %}
                                        <span class="ml-2">{{ user.username }}</span>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right bg-light border-0 rounded">
                                        <a class="dropdown-item" href="{% url 'account:profile_edit' %}">
                                            <i class="fa fa-user-edit mr-2"></i> Edit Profile
                                        </a>
                                        <a class="dropdown-item" href="{% url 'account:logout_user' %}">
                                            <i class="fa fa-sign-out-alt mr-2"></i> Logout
                                        </a>
                                    </div>
                                </li>
                            {% else %}
                                <li class="nav-item ml-auto">
                                    <a class="nav-link text-white" href="{% url 'account:user_login' %}">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" href="{% url 'account:user_register' %}">Register</a>
                                </li>
                            {% endif %}
                        </ul>
                        
                            <!-- دسته‌بندی‌ها در یک Dropdown -->
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" id="categoryDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-list-alt"></i> دسته‌بندی‌ها
                                </a>
                                <div class="dropdown-menu border-0 rounded shadow-sm bg-light" aria-labelledby="categoryDropdown">
                                    {% for category in categories %}
                                        <a class="dropdown-item text-dark" href="{% url 'category-products' category.id %}">
                                            <i class="fa fa-tag"></i> {{ category.name }}
                                        </a>
                                    {% endfor %}
                                </div>
                            </div>
                            <a href="{% url 'home' %}" class="nav-item nav-link active">Home</a>
                            <a href="{% url 'product-list' %}" class="nav-item nav-link">Shop</a>
                        <a href="{% url 'contact' %}" class="nav-item nav-link">Contact</a>

                        {% if user.is_staff %}                          
                        <a href="{% url 'product-management' %}" class="nav-item nav-link">Management</a>
                        {% endif %}                            

                        {% if request.user.is_authenticated %}
                            <a href="{% url 'user_orders' %}" class="nav-item nav-link">Chart</a>
                        {% endif %}

                    </div>

                    <!-- User Account Section -->
                </div>
            </nav>
        </div>
    </div>
</div>
<!-- Navbar End -->




{% block content %}
    
{% endblock %}
    


<!-- Footer Start -->
<div class="container-fluid bg-dark text-secondary mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <h5 class="text-secondary text-uppercase mb-4">Get In Touch</h5>
            <p class="mb-4">No dolore ipsum accusam no lorem. Invidunt sed clita kasd clita et et dolor sed dolor. Rebum
                tempor no vero est magna amet no</p>
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">Quick Shop</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                        <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">My Account</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                        <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">Newsletter</h5>
                    <p>Duo stet tempor ipsum sit amet magna ipsum tempor est</p>
                    <form action="">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Your Email Address">
                            <div class="input-group-append">
                                <button class="btn btn-primary">Sign Up</button>
                            </div>
                        </div>
                    </form>
                    <h6 class="text-secondary text-uppercase mt-4 mb-3">Follow Us</h6>
                    <div class="d-flex">
                        <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                        <a class="btn btn-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-secondary">
                &copy; <a class="text-primary" href="#">Domain</a>. All Rights Reserved. Designed
                by
                <a class="text-primary" href="https://htmlcodex.com">HTML Codex</a>
                <br>Distributed By: <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
            </p>
        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">
            <img class="img-fluid" src="{% static 'img/payments.png' %}" alt="">
        </div>
    </div>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

<!-- Contact Javascript File -->
<script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
<script src="{% static 'mail/contact.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/contact.html
{% extends '_base.html' %}
{% load static %}
{% block content %}

    <!-- Header Start -->
    <div class="container-fluid hero-header py-5 mb-5" style="background-color: #333; color: white;">
        <div class="container py-5">
            <div class="row g-5 align-items-center">
                <div class="col-lg-6">
                    <h1 class="display-4 mb-3 animated slideInDown text-orange" style="text-shadow: 2px 2px 8px rgba(0,0,0,0.4);">تماس با ما</h1>
                    <nav aria-label="breadcrumb animated slideInDown">
                   
                    </nav>
                </div>
                <div class="col-lg-6 animated fadeIn">
                    <img class="img-fluid animated pulse infinite rounded shadow-lg" style="animation-duration: 3s;" src="{% static 'img/hero-2.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->

    <!-- Contact Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="row g-5 mb-5 wow fadeInUp" data-wow-delay="0.1s">
                <div class="col-lg-6">
                    <h1 class="display-6 text-orange">تماس با ما</h1>
                    <p class="text-secondary fs-5 mb-0">اگر سوالی دارید، لطفا با ما تماس بگیرید</p>
                </div>
            </div>
            <div class="row g-5">
                <div class="col-lg-5 col-md-6 wow fadeInUp bg-light p-4 rounded shadow-lg" data-wow-delay="0.1s">
                    <p class="mb-2 text-secondary">دفتر ما:</p>
                    <h4 class="text-orange">خیابان 123، لرستان بروجرد</h4>
                    <hr class="w-100">
                    <p class="mb-2 text-secondary">با ما تماس بگیرید:</p>
                    <h4 class="text-orange">+989339796368</h4>
                    <hr class="w-100">
                    <p class="mb-2 text-secondary">ایمیل ما:</p>
                    <h4 class="text-orange">abolfazlking22@gmail.com</h4>
                    <hr class="w-100">
                    <p class="mb-2 text-secondary">ما را دنبال کنید:</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-square btn-orange rounded-circle me-2 shadow-lg" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-square btn-orange rounded-circle me-2 shadow-lg" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-square btn-orange rounded-circle me-2 shadow-lg" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-square btn-orange rounded-circle me-2 shadow-lg" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-7 col-md-6 wow fadeInUp bg-white p-4 rounded shadow-lg" data-wow-delay="0.5s">
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="col-12">
                            <button class="btn btn-orange py-3 px-4 rounded-pill shadow-lg" type="submit">ارسال پیام</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->


    <style>
        .text-orange {
            color: #ffbb00d0 !important;
        }
        .btn-orange {
            background-color: #ffbb00d0 !important;
            color: white !important;
            border: none;
            transition: all 0.3s ease-in-out;
        }
        .btn-orange:hover {
            background-color: #ffbb00d0 !important;
        }
        .shadow-lg {
            box-shadow: 0 6px 15px rgba(0, 0, 0, 0.2);
        }
        .rounded-pill {
            border-radius: 50px !important;
        }
    </style>

{% endblock %}

templates/index.html
{% extends '_base.html' %}
{% load static %}

{% block content %}
<!-- Carousel Start -->
<div class="container-fluid mb-3">
    <div class="row px-xl-5">
        <div class="col-lg-8">
            <div id="header-carousel" class="carousel slide carousel-fade mb-30 mb-lg-0" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#header-carousel" data-slide-to="0" class="active"></li>
                    <li data-target="#header-carousel" data-slide-to="1"></li>
                    <li data-target="#header-carousel" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item position-relative active" style="height: 430px;">
                        <img class="position-absolute w-100 h-100" src="{% static 'img/carousel-1.jpg' %}" style="object-fit: cover;">
                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                            <div class="p-3" style="max-width: 700px;">
                                <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">Men Fashion</h1>
                                <p class="mx-md-5 px-5 animate__animated animate__bounceIn">Lorem rebum magna amet lorem magna erat diam stet. Sadips duo stet amet amet ndiam elitr ipsum diam</p>
                                <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="#">Shop Now</a>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item position-relative" style="height: 430px;">
                        <img class="position-absolute w-100 h-100" src="{% static 'img/carousel-2.jpg' %}" style="object-fit: cover;">
                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                            <div class="p-3" style="max-width: 700px;">
                                <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">Women Fashion</h1>
                                <p class="mx-md-5 px-5 animate__animated animate__bounceIn">Lorem rebum magna amet lorem magna erat diam stet. Sadips duo stet amet amet ndiam elitr ipsum diam</p>
                                <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="#">Shop Now</a>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item position-relative" style="height: 430px;">
                        <img class="position-absolute w-100 h-100" src="{% static 'img/carousel-3.jpg' %}" style="object-fit: cover;">
                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                            <div class="p-3" style="max-width: 700px;">
                                <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">Kids Fashion</h1>
                                <p class="mx-md-5 px-5 animate__animated animate__bounceIn">Lorem rebum magna amet lorem magna erat diam stet. Sadips duo stet amet amet ndiam elitr ipsum diam</p>
                                <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="#">Shop Now</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="product-offer mb-30" style="height: 200px;">
                <img class="img-fluid" src="{% static 'img/offer-1.jpg' %}" alt="">
                <div class="offer-text">
                    <h6 class="text-white text-uppercase">Save 20%</h6>
                    <h3 class="text-white mb-3">Special Offer</h3>
                    <a href="" class="btn btn-primary">Shop Now</a>
                </div>
            </div>
            <div class="product-offer mb-30" style="height: 200px;">
                <img class="img-fluid" src="{% static 'img/offer-2.jpg' %}" alt="">
                <div class="offer-text">
                    <h6 class="text-white text-uppercase">Save 20%</h6>
                    <h3 class="text-white mb-3">Special Offer</h3>
                    <a href="" class="btn btn-primary">Shop Now</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Carousel End -->
 <!-- Featured Start -->
 <div class="container-fluid pt-5">
    <div class="row px-xl-5 pb-3">
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fa fa-check text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">Quality Product</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fa fa-shipping-fast text-primary m-0 mr-2"></h1>
                <h5 class="font-weight-semi-bold m-0">Free Shipping</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fas fa-exchange-alt text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">14-Day Return</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fa fa-phone-volume text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">24/7 Support</h5>
            </div>
        </div>
    </div>
</div>
<!-- Featured End -->


{##}
{#<!-- Offer Start -->#}
{#<div class="container-fluid pt-5 pb-3">#}
{#    <div class="row px-xl-5">#}
{#        <div class="col-md-6">#}
{#            <div class="product-offer mb-30" style="height: 300px;">#}
{#                <img class="img-fluid" src="{% static 'img/offer-1.jpg' %}" alt="">#}
{#                <div class="offer-text">#}
{#                    <h6 class="text-white text-uppercase">Save 20%</h6>#}
{#                    <h3 class="text-white mb-3">Special Offer</h3>#}
{#                    <a href="" class="btn btn-primary">Shop Now</a>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#        <div class="col-md-6">#}
{#            <div class="product-offer mb-30" style="height: 300px;">#}
{#                <img class="img-fluid" src="{% static 'img/offer-2.jpg' %}" alt="">#}
{#                <div class="offer-text">#}
{#                    <h6 class="text-white text-uppercase">Save 20%</h6>#}
{#                    <h3 class="text-white mb-3">Special Offer</h3>#}
{#                    <a href="" class="btn btn-primary">Shop Now</a>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}
{#<!-- Offer End -->#}




{#<!-- Vendor Start -->#}
{#<div class="container-fluid py-5">#}
{#    <div class="row px-xl-5">#}
{#        <div class="col">#}
{#            <div class="owl-carousel vendor-carousel">#}
{#                <div class="bg-light p-4">#}
{#                    <img src="{% static 'img/vendor-1.jpg' %}" alt="">#}
{#                </div>#}
{#                <div class="bg-light p-4">#}
{#                    <img src="{% static 'img/vendor-2.jpg' %}" alt="">#}
{#                </div>#}
{#                <div class="bg-light p-4">#}
{#                    <img src="{% static 'img/vendor-3.jpg' %}" alt="">#}
{#                </div>#}
{#                <div class="bg-light p-4">#}
{#                    <img src="{% static 'img/vendor-4.jpg' %}" alt="">#}
{#                </div>#}
{#                <div class="bg-light p-4">#}
{#                    <img src="{% static 'img/vendor-5.jpg' %}" alt="">#}
{#                </div>#}
{#                <div class="bg-light p-4">#}
{#                    <img src="{% static 'img/vendor-6.jpg' %}" alt="">#}
{#                </div>#}
{#                <div class="bg-light p-4">#}
{#                    <img src="{% static 'img/vendor-7.jpg' %}" alt="">#}
{#                </div>#}
{#                <div class="bg-light p-4">#}
{#                    <img src="{% static 'img/vendor-8.jpg' %}" alt="">#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}
{#<!-- Vendor End -->#}

{% endblock %}